blank_issues_enabled: false
contact_links:
  - name: Contact Support
    url: https://naninovel.com/support/#developer-support
    about: Please see the website on how to contact the support. We're not providing support via GitHub issues.
